### ISSUE TITLE
Índices

### ISSUE THREAD

**Issue by jpdarabas** [Guzzatti/seguro-imoveis-satc-2023#11]
@jpdarabas Eu crio os índices nas tabelas.

**Comment by jpdarabas** [comment]
CREATE INDEX idx_cobertura ON cobertura (obrigatorio);
CREATE INDEX idx_pagamento ON pagamento (data_pagamento, valor_pagamento);
CREATE INDEX idx_apolice_seguro ON apolice_seguro (data_termino);
CREATE INDEX idx_evento_sinistro ON evento_sinistro (data_sinistro, descricao_sinistro, valor_sinistro);

**Comment by lucasfm20** [comment]
É importante colocar os índices clustered também(coloquei os nomes dos índices no dicionário).

**Comment by jpdarabas** [comment]
> É importante colocar os índices clustered também(coloquei os nomes dos índices no dicionário).

Os clustered já estão declarados no script de criação das tabelas.

**Comment by jpdarabas** [comment]
Índices atualizados:
```MYSQL
CREATE INDEX idx_cobertura ON cobertura (obrigatorio, descricao, premio, limite_indenizacao);
CREATE INDEX idx_pagamento ON pagamento (data_pagamento, valor_pagamento);
CREATE INDEX idx_apolice_seguro ON apolice_seguro (data_termino);
CREATE INDEX idx_evento_sinistro ON evento_sinistro (data_sinistro, descricao_sinistro, valor_sinistro);
```
