### ISSUE TITLE
Criação do modelo ER fisico

### ISSUE THREAD

**Issue by Jotas-V** [Guzzatti/seguro-imoveis-satc-2023#2]
@JoaoVitorRodriguesRocha Favor providenciar criação do modelo ER fisico

**Comment by JoaoVitorRodriguesRocha** [comment]
![Diagrama atualizado](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/2fc7c98c-0063-4d22-bf90-8e3de3e85f28)
@Guzzatti

**Comment by Jotas-V** [comment]
![Diagrama atualizado 2](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/27ea297f-4eeb-4cbb-adbb-493a2d8155af)

@Guzzatti @jpdarabas @lucasfm20 atualizado

**Comment by jpdarabas** [comment]
Acredito que seria melhor criar uma tabela para coberturas, com colunas ID, descrição, prêmio, limite de indenização, id da seguradora, obrigatório (bool). Então na tabela existente de cobertura_seguro teria o id do apólice e id cobertura, onde vai ser inserido cada cobertura de determinado seguro, para ligar essas duas tabelas. Assim o corretor só precisará selecionar as coberturas existentes dentro da seguradora em que ele trabalha.

**Comment by Jotas-V** [comment]
Segue as alterações propostas pelo @jpdarabas 
![image](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/01d06727-3dfe-47ba-a935-14c1aa5fc70b)

**Comment by JoaoVitorRodriguesRocha** [comment]
Segue aqui o diagrama 100% atualizado com todas as novas informações 
![image](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/7fa08d86-c72f-49a8-a39e-155a3d0183b1)

**Comment by Jotas-V** [comment]
Segue aqui o diagrama atualizado 100% com todas as informações e correções 
![Diagrama](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/8ef5dc3f-86f3-4207-ae8d-b68b4bf6dcfa)

**Comment by jpdarabas** [comment]
Acredito que a tabela corretor deveria se ligar com a de apólice em vez de cobertura, por meio da coluna corretor_id e, o número de registro não o liga com uma seguradora, deve ser adicionada uma coluna seguradora_id dentro da tabela corretor pra fazer essa ligação.

**Comment by Guzzatti** [comment]
@JoaoVitorRodriguesRocha estou no aguardo para poder refazer o script do banco ddl

**Comment by Jotas-V** [comment]
![Copy of imóveis-satc](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/cbb4adec-7ab0-4d5b-a809-4249163bdbb8) acho que seria assim

**Comment by jpdarabas** [comment]
A cobertura_seguro deve ter somente apolice_id e cobertura_id, pra ligar as tabelas apólice e cobertura numa ligação muitos pra muitos.

**Comment by Jotas-V** [comment]
![Copy of imóveis-satc (1)](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/46cf138d-68c1-4e66-9403-4d630fd308b2)

**Comment by Guzzatti** [comment]
a cobertura_seguro seria só cobertura_id e apolice_id
ela é só pra ligar a cobertura com apolice em muitos pra muitos

**Comment by jpdarabas** [comment]
Faltou ligar cobertura_id da cobertura (um) com cobertura_seguro (muitos), no apólice id é muitos pra cobertura_seguro e um pra apólice.

**Comment by Jotas-V** [comment]
![Copy of imóveis-satc (2)](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/b52e9793-784b-494f-9b9f-fe3ea3783035)
Se Deus quiser agora está certo

**Comment by jpdarabas** [comment]
Na cobertura_seguro o nome é cobertura_id, ela não possui PK, na tabela cobertura há somente cobertura_id, sem a cobertura_seguro_id. Sugiro também mudar o nome da tabela cobertura_seguro pra cobertura_apolice, para ficar mais claro a utilidade dela como uma tabela intermediária

**Comment by Guzzatti** [comment]
![DBML BD2](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/136494543/abeca983-2a80-43b4-8607-b80539dfc905)

**Comment by Guzzatti** [comment]
Aqui está a versão final do modelo físico (DBML)

**Comment by Jotas-V** [comment]
Correção diagrama, Retirada do UNIQUE 
![Copy of imóveis-satc](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/59bba211-779a-4b9d-8226-4875430fd643)

**Comment by jpdarabas** [comment]
Muda o nome da cobertura_seguro para cobertura_apolice e mude também o nome do id dela, também adicione a coluna cobertura_id pra se ligar com a PK da tabela cobertura, excluindo a cobertura_seguro_id da tabela cobertura. Obrigado!

**Comment by Jotas-V** [comment]
![Copy of imóveis-satc (1)](https://github.com/Guzzatti/seguro-imoveis-satc-2023/assets/103520321/668bf69f-9c48-4186-b19d-7ba6af637f7a)

**Comment by jpdarabas** [comment]
Precisa mudar todos telefones pra varchar(20).
