### ISSUE TITLE
Consultas 

### ISSUE THREAD

**Issue by Guzzatti** [Guzzatti/seguro-imoveis-satc-2023#5]
@lucasfm20 Favor providenciar as consultas que respondem perguntas de negócios (4). Tmj

**Comment by lucasfm20** [comment]
1-Qual é o prêmio total de uma apólice com o ID igual a 1, considerando as coberturas associadas a essa apólice?

SELECT premio_apolice(1) AS premio_total; 


2-Quais são as coberturas obrigatórias para uma seguradora com o ID igual a 2?

SELECT * FROM coberturas_obrigatorias(2);


3-Quais são as apólices de seguro que vencerão até o dia 30/03/2024?

SELECT apolice_id
FROM apolice_seguro a
WHERE a.data_termino BETWEEN CURDATE() AND '2024-03-30';

4-Qual é a cobertura mais cara entre todas as apólices de seguro e qual é o cliente associado a essa cobertura?

SELECT co.descricao,co.cobertura_id, c.nome_cliente, MAX(co.premio) AS premio_maximo
FROM cobertura co
JOIN cobertura_apolice ca ON co.cobertura_id = ca.cobertura_id
JOIN apolice_seguro a ON ca.apolice_id = a.apolice_id
JOIN cliente c ON a.cliente_id = c.cliente_id
GROUP BY co.cobertura_id



5-Quais foram os clientes que tiveram a descrição do sinistro como 'Roubo a residência' e qual é o tipo do seu imovel?

select nome_cliente,descricao_sinistro,tipo_imovel
from cliente c inner join apolice_seguro a
on c.cliente_id = a.cliente_id inner join evento_sinistro e 
on a.apolice_id = e.apolice_id inner join imovel i
on a.imovel_id = i.imovel_id
where descricao_sinistro = 'Roubo na residência'

**Comment by lucasfm20** [comment]
Correção das consultas

3-Quais são as apólices de seguro que vencerão até o dia 30/03/2024?

SELECT apolice_id
FROM apolice_seguro a
WHERE a.data_termino BETWEEN '2023-12-08 AND '2024-03-30';

4-Qual é a cobertura mais cara entre todas as apólices de seguro e qual é o cliente associado a essa cobertura?

SELECT co.descricao,co.cobertura_id, c.nome_cliente, MAX(co.premio) AS premio_maximo
FROM cobertura co
JOIN cobertura_apolice ca ON co.cobertura_id = ca.cobertura_id
JOIN apolice_seguro a ON ca.apolice_id = a.apolice_id
JOIN cliente c ON a.cliente_id = c.cliente_id
GROUP BY co.cobertura_id
ORDER BY premio_maximo DESC
LIMIT 1;

**Comment by lucasfm20** [comment]
Adicionando uma consulta reserva:

6- Faça uma lista de corretores com suas seguradoras e número de ápolices:

SELECT c.nome_corretor, s.nome_seguradora, COUNT(a.apolice_id) AS num_apolices
FROM corretor c
JOIN seguradora s ON c.seguradora_id = s.seguradora_id
JOIN apolice_seguro a ON c.corretor_id = a.corretor_id
GROUP BY c.corretor_id, s.seguradora_id;
