### ISSUE TITLE
Script DDL (Criação BD/Objetos)

### ISSUE THREAD

**Issue by Guzzatti** [Guzzatti/seguro-imoveis-satc-2023#7]
@Guzzatti Eu faço os scripts DDL

**Comment by Guzzatti** [comment]
CREATE TABLE cliente (
    cliente_id INT PRIMARY KEY,
    nome_cliente VARCHAR(255),
    endereco_cliente VARCHAR(255),
    telefone_cliente VARCHAR(15),
    email_cliente VARCHAR(255)
);

CREATE TABLE imovel (
    imovel_id INT PRIMARY KEY,
    cliente_id INT REFERENCES cliente(cliente_id),
    endereco_imovel VARCHAR(255),
    tipo_imovel VARCHAR(50),
    valor_imovel DECIMAL(12, 2)
);


CREATE TABLE apolice_seguro (
    apolice_id INT PRIMARY KEY,
    cliente_id INT UNIQUE REFERENCES cliente(cliente_id),
    imovel_id INT UNIQUE REFERENCES imovel(imovel_id),
    seguradora_id INT REFERENCES seguradora(seguradora_id),
    data_inicio DATE,
    data_termino DATE,
    premio DECIMAL(12, 2)
);


CREATE TABLE cobertura_seguro (
    cobertura_id INT PRIMARY KEY,
    descricao VARCHAR(255),
    corretor_id INT REFERENCES corretor(corretor_id),
    valor_cobertura DECIMAL(10, 2),
    apolice_id INT REFERENCES apolice_seguro(apolice_id)
);


CREATE TABLE pagamento (
    pagamento_id INT PRIMARY KEY,
    apolice_id INT REFERENCES apolice_seguro(apolice_id),
    data_pagamento DATE,
    valor_pagamento DECIMAL(10, 2)
);


CREATE TABLE corretor (
    corretor_id INT PRIMARY KEY,
    nome_corretor VARCHAR(255),
    numero_registro VARCHAR(50),
    seguradora_id INT REFERENCES seguradora(seguradora_id),
    telefone_corretor VARCHAR(15),
    email_corretor VARCHAR(255)
);

CREATE TABLE seguradora (
    seguradora_id INT PRIMARY KEY,
    nome_seguradora VARCHAR(255) UNIQUE,
    endereco_seguradora VARCHAR(255),
    telefone_seguradora VARCHAR(15),
    email_seguradora VARCHAR(255)
);

CREATE TABLE evento_sinistro (
    sinistro_id INT PRIMARY KEY,
    apolice_id INT REFERENCES apolice_seguro(apolice_id),
    data_sinistro DATE,
    descricao_sinistro VARCHAR(255),
    valor_sinistro DECIMAL(12, 2)
);


Scripts DDL feitos!

**Comment by jpdarabas** [comment]
Acredito que seria melhor criar uma tabela para coberturas, com colunas ID, descrição, prêmio, limite de indenização, id da seguradora, obrigatório (bool). Então na tabela existente de cobertura_seguro teria o id do apólice e id cobertura, onde vai ser inserido cada cobertura de determinado seguro, para ligar essas duas tabelas. Assim o corretor só precisará selecionar as coberturas existentes dentro da seguradora em que ele trabalha. Esse mesmo comentário adicionei também à issue do diagrama para facilitar a comunicação.

**Comment by Jotas-V** [comment]
@Guzzatti Arrumar o script ddl de acordo com o diagrama feito
https://github.com/Guzzatti/seguro-imoveis-satc-2023/blob/main/Diagrama%201.png

**Comment by Guzzatti** [comment]
Ok, farei as alterações, mas creio que tem mais mudanças a serem feitas no diagrama para podermos avançar para o código, @JoaoVitorRodriguesRocha

**Comment by Guzzatti** [comment]
CREATE TABLE cliente (
    cliente_id INT PRIMARY KEY,
    nome_cliente VARCHAR(255),
    endereco_cliente VARCHAR(255),
    telefone_cliente VARCHAR(15),
    email_cliente VARCHAR(255)
);

CREATE TABLE imovel (
    imovel_id INT PRIMARY KEY,
    cliente_id INT,
    endereco_imovel VARCHAR(255),
    tipo_imovel VARCHAR(50),
    valor_imovel DECIMAL(12, 2),
    FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id)
);

CREATE TABLE cobertura (
    cobertura_id INT PRIMARY KEY,
    cobertura_seguro_id INT,
    descricao VARCHAR(255),
    premio DECIMAL(12, 2),
    limite_indenizacao DECIMAL(12, 2),
    seguradora_id INT,
    obrigatorio BOOLEAN,
    FOREIGN KEY (cobertura_seguro_id) REFERENCES cobertura_seguro(cobertura_seguro_id),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id)
);

CREATE TABLE apolice_seguro (
    apolice_id INT PRIMARY KEY,
    cliente_id INT UNIQUE,
    imovel_id INT UNIQUE,
    seguradora_id INT,
    corretor_id INT,
    data_inicio DATE,
    data_termino DATE,
    FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id),
    FOREIGN KEY (imovel_id) REFERENCES imovel(imovel_id),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id),
    FOREIGN KEY (corretor_id) REFERENCES corretor(corretor_id)
);

CREATE TABLE cobertura_seguro (
    cobertura_seguro_id INT PRIMARY KEY,
    apolice_id INT,
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);

CREATE TABLE pagamento (
    pagamento_id INT PRIMARY KEY,
    apolice_id INT,
    data_pagamento DATE,
    valor_pagamento DECIMAL(10, 2),
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);

CREATE TABLE corretor (
    corretor_id INT PRIMARY KEY,
    nome_corretor VARCHAR(255),
    numero_registro VARCHAR(50),
    seguradora_id INT,
    telefone_corretor VARCHAR(15),
    email_corretor VARCHAR(255),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id)
);

CREATE TABLE seguradora (
    seguradora_id INT PRIMARY KEY,
    nome_seguradora VARCHAR(255) UNIQUE,
    endereco_seguradora VARCHAR(255),
    telefone_seguradora VARCHAR(15),
    email_seguradora VARCHAR(255)
);

CREATE TABLE evento_sinistro (
    sinistro_id INT PRIMARY KEY,
    apolice_id INT,
    data_sinistro DATE,
    descricao_sinistro VARCHAR(255),
    valor_sinistro DECIMAL(12, 2),
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);

**Comment by Guzzatti** [comment]
Alteração feita conforme mudanças no modelo Físico

**Comment by Guzzatti** [comment]
Conferi e vi que tinha um erro em relação ao autoincremento, que estava faltando nas ids de cada tabela
quando criar um usuario por exemplo não somos nos quem vamos inserir as id
vou refazer

**Comment by Guzzatti** [comment]
CREATE TABLE cliente (
    cliente_id INT AUTO_INCREMENT PRIMARY KEY,
    nome_cliente VARCHAR(255),
    endereco_cliente VARCHAR(255),
    telefone_cliente VARCHAR(15),
    email_cliente VARCHAR(255)
);

CREATE TABLE imovel (
    imovel_id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT,
    endereco_imovel VARCHAR(255),
    tipo_imovel VARCHAR(50),
    valor_imovel DECIMAL(12, 2),
    FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id)
);

CREATE TABLE cobertura (
    cobertura_id INT AUTO_INCREMENT PRIMARY KEY,
    cobertura_seguro_id INT,
    descricao VARCHAR(255),
    premio DECIMAL(12, 2),
    limite_indenizacao DECIMAL(12, 2),
    seguradora_id INT,
    obrigatorio BOOLEAN,
    FOREIGN KEY (cobertura_seguro_id) REFERENCES cobertura_seguro(cobertura_seguro_id),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id)
);

CREATE TABLE apolice_seguro (
    apolice_id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT UNIQUE,
    imovel_id INT UNIQUE,
    seguradora_id INT,
    corretor_id INT,
    data_inicio DATE,
    data_termino DATE,
    FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id),
    FOREIGN KEY (imovel_id) REFERENCES imovel(imovel_id),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id),
    FOREIGN KEY (corretor_id) REFERENCES corretor(corretor_id)
);

CREATE TABLE cobertura_seguro (
    cobertura_seguro_id INT AUTO_INCREMENT PRIMARY KEY,
    apolice_id INT,
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);

CREATE TABLE pagamento (
    pagamento_id INT AUTO_INCREMENT PRIMARY KEY,
    apolice_id INT,
    data_pagamento DATE,
    valor_pagamento DECIMAL(10, 2),
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);

CREATE TABLE corretor (
    corretor_id INT AUTO_INCREMENT PRIMARY KEY,
    nome_corretor VARCHAR(255),
    numero_registro VARCHAR(50),
    seguradora_id INT,
    telefone_corretor VARCHAR(15),
    email_corretor VARCHAR(255),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id)
);

CREATE TABLE seguradora (
    seguradora_id INT AUTO_INCREMENT PRIMARY KEY,
    nome_seguradora VARCHAR(255) UNIQUE,
    endereco_seguradora VARCHAR(255),
    telefone_seguradora VARCHAR(15),
    email_seguradora VARCHAR(255)
);

CREATE TABLE evento_sinistro (
    sinistro_id INT AUTO_INCREMENT PRIMARY KEY,
    apolice_id INT,
    data_sinistro DATE,
    descricao_sinistro VARCHAR(255),
    valor_sinistro DECIMAL(12, 2),
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);

**Comment by Guzzatti** [comment]
Conforme últimas alterações no modelo físico propostas por @jpdarabas aqui está o script SQL final

CREATE TABLE cliente (
    cliente_id INT AUTO_INCREMENT PRIMARY KEY,
    nome_cliente VARCHAR(255),
    endereco_cliente VARCHAR(255),
    telefone_cliente VARCHAR(15),
    email_cliente VARCHAR(255)
);

CREATE TABLE imovel (
    imovel_id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT,
    endereco_imovel VARCHAR(255),
    tipo_imovel VARCHAR(50),
    valor_imovel DECIMAL(12, 2),
    FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id)
);

CREATE TABLE cobertura (
    cobertura_id INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(255),
    premio DECIMAL(12, 2),
    limite_indenizacao DECIMAL(12, 2),
    seguradora_id INT,
    obrigatorio BOOLEAN,
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id)
);

CREATE TABLE apolice_seguro (
    apolice_id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT UNIQUE,
    imovel_id INT UNIQUE,
    seguradora_id INT,
    corretor_id INT,
    data_inicio DATE,
    data_termino DATE,
    FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id),
    FOREIGN KEY (imovel_id) REFERENCES imovel(imovel_id),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id),
    FOREIGN KEY (corretor_id) REFERENCES corretor(corretor_id)
);

CREATE TABLE cobertura_apolice (  -- Renamed from cobertura_seguro
    cobertura_apolice_id INT AUTO_INCREMENT PRIMARY KEY,
    apolice_id INT,
    cobertura_id INT,
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id),
    FOREIGN KEY (cobertura_id) REFERENCES cobertura(cobertura_id)
);

CREATE TABLE pagamento (
    pagamento_id INT AUTO_INCREMENT PRIMARY KEY,
    apolice_id INT,
    data_pagamento DATE,
    valor_pagamento DECIMAL(10, 2),
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);

CREATE TABLE corretor (
    corretor_id INT AUTO_INCREMENT PRIMARY KEY,
    nome_corretor VARCHAR(255),
    numero_registro VARCHAR(50),
    seguradora_id INT,
    telefone_corretor VARCHAR(15),
    email_corretor VARCHAR(255),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id)
);

CREATE TABLE seguradora (
    seguradora_id INT AUTO_INCREMENT PRIMARY KEY,
    nome_seguradora VARCHAR(255) UNIQUE,
    endereco_seguradora VARCHAR(255),
    telefone_seguradora VARCHAR(15),
    email_seguradora VARCHAR(255)
);

CREATE TABLE evento_sinistro (
    sinistro_id INT AUTO_INCREMENT PRIMARY KEY,
    apolice_id INT,
    data_sinistro DATE,
    descricao_sinistro VARCHAR(255),
    valor_sinistro DECIMAL(12, 2),
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);

**Comment by Guzzatti** [comment]
CREATE TABLE cliente (
    cliente_id INT AUTO_INCREMENT PRIMARY KEY,
    nome_cliente VARCHAR(255),
    endereco_cliente VARCHAR(255),
    telefone_cliente VARCHAR(20),
    email_cliente VARCHAR(255)
);

CREATE TABLE imovel (
    imovel_id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT,
    endereco_imovel VARCHAR(255),
    tipo_imovel VARCHAR(50),
    valor_imovel DECIMAL(12, 2),
    FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id)
);

CREATE TABLE cobertura (
    cobertura_id INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(255),
    premio DECIMAL(12, 2),
    limite_indenizacao DECIMAL(12, 2),
    seguradora_id INT,
    obrigatorio BOOLEAN,
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id)
);

CREATE TABLE apolice_seguro (
    apolice_id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT ,
    imovel_id INT ,
    seguradora_id INT,
    corretor_id INT,
    data_inicio DATE,
    data_termino DATE,
    FOREIGN KEY (cliente_id) REFERENCES cliente(cliente_id),
    FOREIGN KEY (imovel_id) REFERENCES imovel(imovel_id),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id),
    FOREIGN KEY (corretor_id) REFERENCES corretor(corretor_id)
);

CREATE TABLE cobertura_apolice ( 
    cobertura_apolice_id INT AUTO_INCREMENT PRIMARY KEY,
    apolice_id INT,
    cobertura_id INT,
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id),
    FOREIGN KEY (cobertura_id) REFERENCES cobertura(cobertura_id)
);

CREATE TABLE pagamento (
    pagamento_id INT AUTO_INCREMENT PRIMARY KEY,
    apolice_id INT,
    data_pagamento DATE,
    valor_pagamento DECIMAL(10, 2),
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);

CREATE TABLE corretor (
    corretor_id INT AUTO_INCREMENT PRIMARY KEY,
    nome_corretor VARCHAR(255),
    numero_registro VARCHAR(50),
    seguradora_id INT,
    telefone_corretor VARCHAR(20),
    email_corretor VARCHAR(255),
    FOREIGN KEY (seguradora_id) REFERENCES seguradora(seguradora_id)
);

CREATE TABLE seguradora (
    seguradora_id INT AUTO_INCREMENT PRIMARY KEY,
    nome_seguradora VARCHAR(255) ,
    endereco_seguradora VARCHAR(255),
    telefone_seguradora VARCHAR(20),
    email_seguradora VARCHAR(255)
);

CREATE TABLE evento_sinistro (
    sinistro_id INT AUTO_INCREMENT PRIMARY KEY,
    apolice_id INT,
    data_sinistro DATE,
    descricao_sinistro VARCHAR(255),
    valor_sinistro DECIMAL(12, 2),
    FOREIGN KEY (apolice_id) REFERENCES apolice_seguro(apolice_id)
);


Alterei varchar dos telefones
