### ISSUE TITLE
Scripts DML (Massa de dados)

### ISSUE THREAD

**Issue by Guzzatti** [Guzzatti/seguro-imoveis-satc-2023#8]
@JoaoVitorRodriguesRocha Favor providenciar os scripts DML para o grupo. Tmj

**Comment by Jotas-V** [comment]
Massa de dados está feita, ja dei commit, @Guzzatti @jpdarabas @lucasfm20 só confirmem se está tudo ok

**Comment by Guzzatti** [comment]
Conferido. Script está Ok, porém tive que alterar o varchar de todos os telefones no script ddl de 12 para 20 para que não houvessem problemas em relação ao número de telefone. Resolvido
